### ISSUE TITLE
Install fails because `ERG_PATH` is not set as an environment variable during the first installation with ergup

### ISSUE THREAD

**Issue by toddlerer** [mtshiba/ergup#5]
The installation of ergup uses poise's `install` command, which reads the `ERG_PATH` environment variable, which fails because it is not set during the initial installation.
https://github.com/mtshiba/ergup/blob/ec0adb5667d8b47caba8e1b4315eaa366fe7380a/ergup.er#L88
https://github.com/erg-lang/poise/blob/bf31e0d3b3320e05c3a765643b57b0ba9f8b568e/src/install.er#L27

**Comment by mtshiba** [comment]
Fixed in https://github.com/erg-lang/poise/commit/4b8a41086b8b8705cbf837bd08c0c45bbc178188.

poise defaults to `$HOME/.erg` when it cannot find `ERG_PATH`. Actually, ergup uses that as the .erg location, so there is no problem with this, but I forgot to set the default value in one place.
